// This file is auto-generated by Lovable. Do not modify it.

// If Lovable injects a runtime object, surface it here; otherwise provide a safe
// fallback to avoid build-time/runtime errors.
const _maybeLovable = (globalThis as any).__lovable ?? {};

export const lovable: Record<string, unknown> = _maybeLovable;
export default lovable;
